# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGx8zwP8INSosVhah6LMzCVsHd25mz3l
"""

!pip install -q POT hmmlearn

import json
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import ot  # Python Optimal Transport library
from scipy.cluster.hierarchy import linkage, cophenet, dendrogram
from scipy.spatial.distance import squareform, euclidean
import matplotlib.pyplot as plt
from collections import Counter

# 1. Load and Clean Data
file_path = '/content/indus_full_dataset.json'
with open(file_path, 'r') as f:
    data = json.load(f)
df = pd.DataFrame(data)

def clean_texts(text_list):
    cleaned = []
    for entry in text_list:
        entry_str = str(entry).replace('*', '').strip()
        if entry_str.isdigit():
            cleaned.append(int(entry_str))
    return cleaned

df['texts'] = df['texts'].apply(clean_texts)
df = df[df['texts'].apply(len) > 0].reset_index(drop=True)
corpus_original = df['texts'].tolist()

# 2. Vocabulary Mapping
all_tokens = [token for sublist in corpus_original for token in sublist]
all_unique_signs = sorted(list(set(all_tokens)))
sign_to_idx = {sign: idx for idx, sign in enumerate(all_unique_signs)}
idx_to_sign = {idx: sign for sign, idx in sign_to_idx.items()}
remapped_vocab_size = len(all_unique_signs)
corpus_original_remapped = [[sign_to_idx[s] for s in seq] for seq in corpus_original]

print(f"Data Loaded. Vocabulary Size: {remapped_vocab_size}")

look_back = 5
emb_dim = 64
lstm_units = 128

# 1. Create Sliding Windows
X_signs, y = [], []
for seq in corpus_original_remapped:
    if len(seq) > look_back:
        for i in range(len(seq) - look_back):
            X_signs.append(seq[i : i + look_back])
            y.append(seq[i + look_back])

X_signs, y = np.array(X_signs), np.array(y)

# 2. Define Model
inputs = keras.Input(shape=(look_back,), name="input")
x = layers.Embedding(input_dim=remapped_vocab_size, output_dim=emb_dim, name="embedding")(inputs)
lstm_out = layers.LSTM(lstm_units, name="lstm_layer")(x)
outputs = layers.Dense(remapped_vocab_size, activation='softmax', name="output")(lstm_out)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

# 3. Train briefly to learn structure
print("Training Model to learn sequence syntax...")
model.fit(X_signs, y, epochs=10, batch_size=64, verbose=1)

# 4. Extract Contextual Hidden States
intermediate_model = keras.Model(inputs=model.input, outputs=model.get_layer("lstm_layer").output)
print("\nExtracting contextual hidden states...")
hidden_states = intermediate_model.predict(X_signs)

print(f"Shape of Hidden States: {hidden_states.shape}")

# Find the Top 40 most frequent signs to keep compute time low
top_signs_indices = [item[0] for item in Counter(y).most_common(40)]

# Dictionary to hold the distribution of vectors for each sign
sign_distributions = {sign: [] for sign in top_signs_indices}

for i in range(len(y)):
    target_sign = y[i]
    if target_sign in top_signs_indices:
        sign_distributions[target_sign].append(hidden_states[i])

# Convert lists to numpy arrays and subsample to max 100 contexts per sign to speed up Optimal Transport
max_samples_per_sign = 100
for sign in top_signs_indices:
    dist = np.array(sign_distributions[sign])
    if len(dist) > max_samples_per_sign:
        # Randomly subsample
        indices = np.random.choice(len(dist), max_samples_per_sign, replace=False)
        dist = dist[indices]
    sign_distributions[sign] = dist

print(f"Created Contextual Distributions for {len(top_signs_indices)} top signs.")

num_signs = len(top_signs_indices)
L2_distance_matrix = np.zeros((num_signs, num_signs))
EMD_distance_matrix = np.zeros((num_signs, num_signs))

print("Calculating Distance Matrices. This may take 1-2 minutes...")

for i in range(num_signs):
    for j in range(i + 1, num_signs):
        sign_A = top_signs_indices[i]
        sign_B = top_signs_indices[j]

        dist_A = sign_distributions[sign_A]
        dist_B = sign_distributions[sign_B]

        # 1.Euclidean distance between Centroids
        mean_A = np.mean(dist_A, axis=0)
        mean_B = np.mean(dist_B, axis=0)
        l2_dist = euclidean(mean_A, mean_B)
        L2_distance_matrix[i, j] = l2_dist
        L2_distance_matrix[j, i] = l2_dist

        # Create uniform weights for the samples
        weights_A = np.ones((len(dist_A),)) / len(dist_A)
        weights_B = np.ones((len(dist_B),)) / len(dist_B)

        # Compute cost matrix between all points in Dist A and Dist B
        cost_matrix = ot.dist(dist_A, dist_B, metric='euclidean')

        # Calculate exact EMD
        emd_dist = ot.emd2(weights_A, weights_B, cost_matrix)
        EMD_distance_matrix[i, j] = emd_dist
        EMD_distance_matrix[j, i] = emd_dist

print("Distance Matrices computed successfully.")

# Convert to condensed distance matrices for scipy
l2_condensed = squareform(L2_distance_matrix)
emd_condensed = squareform(EMD_distance_matrix)

# Perform Hierarchical Clustering
Z_l2 = linkage(l2_condensed, 'average')
Z_emd = linkage(emd_condensed, 'average')

# Calculate CPCC (Cophenetic Correlation Coefficient)
cpcc_l2, _ = cophenet(Z_l2, l2_condensed)
cpcc_emd, _ = cophenet(Z_emd, emd_condensed)

print("--- RESULTS ---")
print(f"Euclidean (L2) Centroid CPCC: {cpcc_l2:.4f}")
print(f"Optimal Transport (EMD) CPCC: {cpcc_emd:.4f}")

# Visualize the Optimal Transport Tree
plt.figure(figsize=(14, 6))
plt.title(f"Unsupervised Syntax Tree Discovered via EMD (CPCC: {cpcc_emd:.4f})", fontsize=14)
# Map indices back to original Mahadevan Sign IDs for the labels
labels = [idx_to_sign[idx] for idx in top_signs_indices]
dendrogram(Z_emd, labels=labels, leaf_rotation=90, leaf_font_size=10)
plt.xlabel("Original Mahadevan Sign ID")
plt.ylabel("Earth Mover's Distance")
plt.show()

import numpy as np
import ot
from scipy.stats import pearsonr
from collections import defaultdict, Counter

print("--- Testing the MTCC (Markov-Transport Correlation) Hypothesis ---")

# 1. Select the top 20 signs to keep computation fast
top_signs = [item[0] for item in Counter(y).most_common(20)]
num_signs = len(top_signs)

# 2. Calculate the Ground Truth Empirical Transition Cost: -log(P(B|A))
transition_counts = defaultdict(lambda: defaultdict(int))
for seq in corpus_original_remapped:
    for i in range(len(seq) - 1):
        transition_counts[seq[i]][seq[i+1]] += 1

empirical_cost_matrix = np.zeros((num_signs, num_signs))
for i, sign_A in enumerate(top_signs):
    total_transitions = sum(transition_counts[sign_A].values())
    for j, sign_B in enumerate(top_signs):
        prob = transition_counts[sign_A][sign_B] / (total_transitions + 1e-9)
        empirical_cost_matrix[i, j] = -np.log(prob + 1e-5)

# 3. Extract Latent Context Distributions
# H_A: Hidden states when the current sign is A
# H_pre_B: Hidden states when the NEXT sign is B
H_current = {sign: [] for sign in top_signs}
H_pre_next = {sign: [] for sign in top_signs}

# We look at the last sign in our look_back window as the "current sign" and the next sign as the "next sign"
next_signs = y

for idx in range(len(hidden_states)):
    curr_s = current_signs[idx]
    next_s = next_signs[idx]

    if curr_s in top_signs:
        H_current[curr_s].append(hidden_states[idx])
    if next_s in top_signs:
        H_pre_next[next_s].append(hidden_states[idx])

# Subsample to max 50 points per sign for fast EMD calculation
for s in top_signs:
    if len(H_current[s]) > 50:
        H_current[s] = np.array(H_current[s])[np.random.choice(len(H_current[s]), 50, replace=False)]
    if len(H_pre_next[s]) > 50:
        H_pre_next[s] = np.array(H_pre_next[s])[np.random.choice(len(H_pre_next[s]), 50, replace=False)]

# 4. Calculate Asymmetric Latent OT Matrix
latent_ot_matrix = np.zeros((num_signs, num_signs))
print("Calculating Asymmetric Earth Mover's Distance...")

for i, sign_A in enumerate(top_signs):
    dist_A = np.array(H_current[sign_A])
    for j, sign_B in enumerate(top_signs):
        dist_pre_B = np.array(H_pre_next[sign_B])

        # If either distribution is empty, assign maximum cost
        if len(dist_A) == 0 or len(dist_pre_B) == 0:
            latent_ot_matrix[i, j] = np.max(latent_ot_matrix) if np.max(latent_ot_matrix) > 0 else 10.0
            continue

        weights_A = np.ones(len(dist_A)) / len(dist_A)
        weights_B = np.ones(len(dist_pre_B)) / len(dist_pre_B)

        # Cost matrix between contexts
        cost_mat = ot.dist(dist_A, dist_pre_B, metric='cosine')

        # Calculate Earth Mover's Distance from A to pre-B
        emd_cost = ot.emd2(weights_A, weights_B, cost_mat)
        latent_ot_matrix[i, j] = emd_cost

# 5. Flatten matrices to calculate Pearson Correlation
emp_flat = empirical_cost_matrix.flatten()
lat_flat = latent_ot_matrix.flatten()

# Calculate MTCC
mtcc_score, p_value = pearsonr(emp_flat, lat_flat)

print("\n--- CONCLUSION ---")
print(f"Markov-Transport Correlation Coefficient (MTCC): {mtcc_score:.4f}")
print(f"P-value: {p_value:.4e}")

